authNProviders=jwt, basic

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/auth/realms/Demo/protocol/openid-connect/certs
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://keycloak-05.ru-central1.internal:8443/auth/realms/Demo/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.opaque-token.introspection-uri=http://localhost:8080/auth/realms/Demo/protocol/openid-connect/token/introspect
spring.security.oauth2.resourceserver.opaque-token.client-id=cmj
spring.security.oauth2.resourceserver.opaque-token.client-secret=4ROjVntZtFFmJVeNxV0frR7mFXQPya5V
#cmj.opaque-token.introspection.authorization.grant.type=password
#cmj.opaque-token.introspection.authentication.method=post
#spring.security.oauth2.resourceserver.opaque-token.use-user-info=true
#cmj.opaque-token.introspection.userinfo-uri=http://localhost:8080/auth/realms/Demo/protocol/openid-connect/userinfo



#Avanpost FAM
#authNProviders=jwt, basic, header
#useOidcProviderMeta=true
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://apidp.ru
#spring.security.oauth2.resourceserver.opaque-token.introspection-uri=https://apidp.ru/oauth2/token/introspect
#spring.security.oauth2.resourceserver.opaque-token.client-id=36dcd475-5fd5-4c25-8ed8-dde7cd4b4ee8
#spring.security.oauth2.resourceserver.opaque-token.client-id=
#spring.security.oauth2.resourceserver.opaque-token.client-secret=cmjserver
#spring.security.oauth2.resourceserver.opaque-token.client-secret=
#spring.security.oauth2.resourceserver.opaque-token.introspection.authentication.method=user_access_token
#spring.security.oauth2.resourceserver.opaque-token.use-user-info=true
#cmj.claim.user-name=sub
#cmj.opaque-token.introspection.authorization.grant.type=user_access_token